"""Demo data so the app works without an LLM API key."""

SEED_STORIES = [
    {
        "rank": 1,
        "headline": "GPT-5 hits human-level math",
        "tag": "MODELS",
        "easy": "An AI cracked 90% of elite math contest problems — a level only genius humans could reach before.",
        "medium": "GPT-5 scores 90% on AIME using chain-of-thought + self-consistency. Frontier LLMs are closing in on expert symbolic reasoning.",
        "pro": "GPT-5 achieves 90% pass@1 on AIME via process reward models (PRMs), supervising reasoning chains rather than just final outputs.",
        "sources": ["The Batch", "TLDR AI"],
    },
    {
        "rank": 2,
        "headline": "EU AI Act enforcement live",
        "tag": "POLICY",
        "easy": "Europe's new AI rules are being enforced. Companies using AI in hiring or healthcare must comply or face huge fines.",
        "medium": "The EU AI Act's high-risk provisions are live. Recruitment and healthcare apps now need conformity assessments and human oversight.",
        "pro": "Annex III systems face FRIA obligations. GPAI models above 10^25 FLOPs trigger systemic-risk provisions including mandatory red-teaming.",
        "sources": ["Import AI", "Stratechery"],
    },
    {
        "rank": 3,
        "headline": "Anthropic ships multi-agent framework",
        "tag": "AGENTS",
        "easy": "Anthropic built a tool that lets many AIs work as a team — different AIs split up different parts of a task.",
        "medium": "Anthropic's framework lets orchestrator agents delegate to sub-agents via API, running subtasks in parallel — great for research pipelines.",
        "pro": "The layer implements typed inter-agent message passing with MCP-compatible interfaces and configurable trust boundaries per agent node.",
        "sources": ["TLDR AI"],
    },
    {
        "rank": 4,
        "headline": "NVIDIA GB300 benchmarks leak",
        "tag": "HARDWARE",
        "easy": "NVIDIA's newest AI chip is reportedly 3x faster than the last one — meaning AI could respond much quicker very soon.",
        "medium": "Leaked GB300 benchmarks show ~3x throughput over H100. Expect big latency drops for inference and cheaper API calls.",
        "pro": "GB300 ships with HBM4 and FP4 Transformer Engine. The ~4.8 TB/s memory bandwidth alleviates the KV cache bottleneck for long-context inference.",
        "sources": ["The Batch", "TLDR AI"],
    },
    {
        "rank": 5,
        "headline": "OpenAI publishes alignment roadmap",
        "tag": "SAFETY",
        "easy": "OpenAI shared a plan to keep their AI safe as it gets smarter — helpful but not dangerous.",
        "medium": "OpenAI's roadmap outlines four safety tiers tied to capability milestones, with scalable oversight and automated red-teaming.",
        "pro": "The roadmap formalizes superalignment: training a weak supervisor to oversee stronger models using debate, amplification, and AI-generated feedback.",
        "sources": ["Import AI"],
    },
    {
        "rank": 6,
        "headline": "AlphaFold 3 expands to RNA",
        "tag": "RESEARCH",
        "easy": "DeepMind's protein-folding AI now works on RNA too — which could massively speed up drug discovery.",
        "medium": "AlphaFold 3 extends to RNA and DNA-protein complexes. Researchers are already using it to screen drug binding sites.",
        "pro": "AlphaFold 3's diffusion-based architecture replaces the evoformer, enabling atom-level precision on nucleic acids for ribozyme and CRISPR guide RNA optimisation.",
        "sources": ["The Batch", "Import AI"],
    },
    {
        "rank": 7,
        "headline": "Claude gets persistent memory",
        "tag": "PRODUCTS",
        "easy": "Claude can now remember things from past conversations — like a friend who recalls what you said before.",
        "medium": "Claude supports persistent memory via opt-in storage, building a user profile across sessions without re-prompting.",
        "pro": "Claude's memory uses a vector-store retrieval layer with salience-filtered writes and embedding-similarity ranked retrieval. Editable via settings.",
        "sources": ["TLDR AI", "Stratechery"],
    },
    {
        "rank": 8,
        "headline": "Mistral drops free 24B model",
        "tag": "OPEN SRC",
        "easy": "A European AI company released a smart free model anyone can download. Surprisingly good for its size.",
        "medium": "Mistral's 24B model matches GPT-4o on benchmarks with full open weights — self-hostable, great for privacy and cost.",
        "pro": "Mistral-Small-3.1 uses grouped-query attention, 128k context, and LoRA-friendly design. Fits on a single A100 80GB under fp16.",
        "sources": ["TLDR AI"],
    },
    {
        "rank": 9,
        "headline": "Inference costs fell 90% in 18mo",
        "tag": "TRENDS",
        "easy": "Running AI has gotten 90% cheaper in 18 months — meaning more people and companies can afford it every day.",
        "medium": "Token prices dropped ~90% since Jan 2023. Inference is commoditising fast, squeezing pure-play API revenue.",
        "pro": "Jevons paradox: 90% cost-per-token drop drove 50x demand growth. Proprietary fine-tuning and deployment layers are the new moat.",
        "sources": ["Stratechery", "Import AI"],
    },
]

SEED_QUIZ = [
    {
        "id": 1,
        "story_rank": 1,
        "question": "What milestone did GPT-5 hit on math benchmarks?",
        "options": [
            "Beat world chess champion",
            "Scored 90% on competition math",
            "Passed the Bar exam",
            "Solved protein folding",
        ],
        "correct_index": 1,
        "explanation": "GPT-5 scored 90% on AIME, a challenging competition math benchmark.",
    },
    {
        "id": 2,
        "story_rank": 3,
        "question": "Which framework lets multiple AI agents work as a team?",
        "options": [
            "OpenAI Swarm",
            "LangChain v4",
            "Anthropic multi-agent",
            "DeepMind Gemini",
        ],
        "correct_index": 2,
        "explanation": "Anthropic shipped a multi-agent framework with typed inter-agent message passing.",
    },
    {
        "id": 3,
        "story_rank": 6,
        "question": "What did AlphaFold 3 expand to predict?",
        "options": [
            "Weather patterns",
            "RNA and DNA structures",
            "Stock prices",
            "Protein timing",
        ],
        "correct_index": 1,
        "explanation": "AlphaFold 3 extended from proteins to RNA and DNA-protein complexes.",
    },
    {
        "id": 4,
        "story_rank": 9,
        "question": "By how much did AI inference costs fall in 18 months?",
        "options": ["10%", "40%", "70%", "90%"],
        "correct_index": 3,
        "explanation": "Token prices dropped approximately 90% since January 2023.",
    },
]

SEED_SOURCES = [
    {"name": "@sama", "source_type": "twitter"},
    {"name": "@karpathy", "source_type": "twitter"},
    {"name": "@ylecun", "source_type": "twitter"},
    {"name": "@OpenAI", "source_type": "twitter"},
    {"name": "@AnthropicAI", "source_type": "twitter"},
    {"name": "TLDR AI", "source_type": "newsletter"},
    {"name": "The Batch", "source_type": "newsletter"},
    {"name": "Import AI", "source_type": "newsletter"},
    {"name": "Stratechery", "source_type": "newsletter"},
    {"name": "Lenny's", "source_type": "newsletter"},
]

RSS_CATALOG = [
    # News outlets
    {
        "name": "MIT Technology Review - AI",
        "url": "https://www.technologyreview.com/topic/artificial-intelligence/feed",
        "source_type": "rss",
        "category": "news",
    },
    {
        "name": "TechCrunch - AI",
        "url": "https://techcrunch.com/category/artificial-intelligence/feed/",
        "source_type": "rss",
        "category": "news",
    },
    {
        "name": "The Verge - AI",
        "url": "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
        "source_type": "rss",
        "category": "news",
    },
    {
        "name": "Ars Technica - AI",
        "url": "https://feeds.arstechnica.com/arstechnica/features",
        "source_type": "rss",
        "category": "news",
    },
    # AI Labs
    {
        "name": "OpenAI Blog",
        "url": "https://openai.com/blog/rss.xml",
        "source_type": "rss",
        "category": "labs",
    },
    {
        "name": "Anthropic News",
        "url": "https://www.anthropic.com/rss.xml",
        "source_type": "rss",
        "category": "labs",
    },
    {
        "name": "Google AI Blog",
        "url": "https://blog.google/technology/ai/rss/",
        "source_type": "rss",
        "category": "labs",
    },
    {
        "name": "Hugging Face Blog",
        "url": "https://huggingface.co/blog/feed.xml",
        "source_type": "rss",
        "category": "labs",
    },
    {
        "name": "DeepMind Blog",
        "url": "https://deepmind.google/blog/rss.xml",
        "source_type": "rss",
        "category": "labs",
    },
    {
        "name": "Meta AI Blog",
        "url": "https://engineering.fb.com/feed/",
        "source_type": "rss",
        "category": "labs",
    },
    # Community
    {
        "name": "r/MachineLearning",
        "url": "https://www.reddit.com/r/MachineLearning/.rss",
        "source_type": "rss",
        "category": "community",
    },
    {
        "name": "r/artificial",
        "url": "https://www.reddit.com/r/artificial/.rss",
        "source_type": "rss",
        "category": "community",
    },
    # Research
    {
        "name": "ArXiv CS.AI",
        "url": "https://rss.arxiv.org/rss/cs.AI",
        "source_type": "rss",
        "category": "research",
    },
    # Twitter/X via Nitter (may be unreliable — depends on instance availability)
    {
        "name": "@karpathy",
        "url": "https://nitter.poast.org/karpathy/rss",
        "source_type": "rss",
        "category": "twitter",
    },
    {
        "name": "@sama",
        "url": "https://nitter.poast.org/sama/rss",
        "source_type": "rss",
        "category": "twitter",
    },
    {
        "name": "@OpenAI",
        "url": "https://nitter.poast.org/OpenAI/rss",
        "source_type": "rss",
        "category": "twitter",
    },
    {
        "name": "@AnthropicAI",
        "url": "https://nitter.poast.org/AnthropicAI/rss",
        "source_type": "rss",
        "category": "twitter",
    },
    {
        "name": "@GoogleAI",
        "url": "https://nitter.poast.org/GoogleAI/rss",
        "source_type": "rss",
        "category": "twitter",
    },
    {
        "name": "@huggingface",
        "url": "https://nitter.poast.org/huggingface/rss",
        "source_type": "rss",
        "category": "twitter",
    },
]
